/**
 * Generates css/_sources.css with absolute @source paths for Tailwind CSS.
 *
 * When the theme is symlinked (common during development), Tailwind resolves
 * @source relative paths from the CSS file's real location, not the symlink.
 * This script uses $PWD (which preserves the symlink path) to generate
 * absolute @source paths that work regardless of symlinks.
 */
const fs = require('fs');
const path = require('path');

const themeDir = process.env.PWD || process.cwd();
const userDir = path.resolve(themeDir, '../..');
const sources = [];

['pages', 'config'].forEach(dir => {
    const fullPath = path.join(userDir, dir);
    if (fs.existsSync(fullPath)) {
        sources.push(`@source "${fullPath}";`);
    }
});

// Check for sandbox-support plugin templates
const sandboxTemplates = path.join(userDir, 'plugins', 'sandbox-support', 'templates');
if (fs.existsSync(sandboxTemplates)) {
    sources.push(`@source "${sandboxTemplates}";`);
}

const content = sources.length > 0
    ? `/* Auto-generated by scripts/resolve-sources.js - do not edit */\n${sources.join('\n')}\n`
    : `/* No external Grav sources detected */\n`;

const outputPath = path.join(__dirname, '..', 'css', '_sources.css');
fs.writeFileSync(outputPath, content);
console.log(`Generated css/_sources.css (${sources.length} source path(s))`);
