[Interface]
PrivateKey = [YOUR_PRIVATE_KEY]  # From your 'privatekey' file on your Gaming PC
Address = 10.0.8.2/24

[Peer]
PublicKey = 0CVFhXtS38yWMFynMmKfsmKt7HvMi0RLIXf1Y5w/ISk=
Endpoint = vpn.tsengel.de:13231
AllowedIPs = 192.168.88.0/24
PersistentKeepalive = 25
